export const ETH_CHAIN_ID = 1
export const OPTIMISM_CHAIN_ID = 10
export const BINANCE_CHAIN_ID = 56
export const POLYGON_CHAIN_ID = 137
export const ARBITRUM_CHAIN_ID = 42161
export const AVALANCHE_CHAIN_ID = 43114

export const CHAIN_ID_ARRAY = [
  ETH_CHAIN_ID,
  OPTIMISM_CHAIN_ID,
  BINANCE_CHAIN_ID,
  POLYGON_CHAIN_ID,
  ARBITRUM_CHAIN_ID,
  AVALANCHE_CHAIN_ID,
]

export type ChainIds =
  | typeof ETH_CHAIN_ID
  | typeof OPTIMISM_CHAIN_ID
  | typeof BINANCE_CHAIN_ID
  | typeof POLYGON_CHAIN_ID
  | typeof ARBITRUM_CHAIN_ID
  | typeof AVALANCHE_CHAIN_ID
