export const ETH_LAYER_ZERO_CHAIN_ID: number = 101
export const BNB_LAYER_ZERO_CHAIN_ID: number = 102
export const AVALANCHE_LAYER_ZERO_CHAIN_ID: number = 106
export const POLYGON_LAYER_ZERO_CHAIN_ID: number = 109
export const ARBITRUM_LAYER_ZERO_CHAIN_ID: number = 110
export const OPTIMISM_LAYER_ZERO_CHAIN_ID: number = 111
export const FANTOM_LAYER_ZERO_CHAIN_ID: number = 112
export const METIS_LAYER_ZERO_CHAIN_ID: number = 151
export const KAVA_LAYER_ZERO_CHAIN_ID: number = 177
export const LINEA_LAYER_ZERO_CHAIN_ID: number = 183
export const BASE_LAYER_ZERO_CHAIN_ID: number = 184

export const LAYER_ZERO_TO_LAYER_ONE_CHAIN_ID: Record<number, number> = {
  [ETH_LAYER_ZERO_CHAIN_ID]: 1,
  [BNB_LAYER_ZERO_CHAIN_ID]: 56,
  [AVALANCHE_LAYER_ZERO_CHAIN_ID]: 43114,
  [POLYGON_LAYER_ZERO_CHAIN_ID]: 137,
  [ARBITRUM_LAYER_ZERO_CHAIN_ID]: 42161,
  [OPTIMISM_LAYER_ZERO_CHAIN_ID]: 10,
  [FANTOM_LAYER_ZERO_CHAIN_ID]: 250,
  [METIS_LAYER_ZERO_CHAIN_ID]: 1088,
  [KAVA_LAYER_ZERO_CHAIN_ID]: 2222,
  [LINEA_LAYER_ZERO_CHAIN_ID]: 59144,
  [BASE_LAYER_ZERO_CHAIN_ID]: 8453,
}

export const CHAIN_ID_ARRAY = [
  ETH_LAYER_ZERO_CHAIN_ID,
  BNB_LAYER_ZERO_CHAIN_ID,
  AVALANCHE_LAYER_ZERO_CHAIN_ID,
  POLYGON_LAYER_ZERO_CHAIN_ID,
  ARBITRUM_LAYER_ZERO_CHAIN_ID,
  OPTIMISM_LAYER_ZERO_CHAIN_ID,
  FANTOM_LAYER_ZERO_CHAIN_ID,
  METIS_LAYER_ZERO_CHAIN_ID,
  KAVA_LAYER_ZERO_CHAIN_ID,
  LINEA_LAYER_ZERO_CHAIN_ID,
  BASE_LAYER_ZERO_CHAIN_ID,
] as const
