export const ETH_CHAIN_ID = 1
export const OPTIMISM_CHAIN_ID = 10
export const ARBITRUM_CHAIN_ID = 42161
export const ZKSYNC_CHAIN_ID = 324
export const BASE_CHAIN_ID = 8453
export const POLYGON_CHAIN_ID = 137
export const CHAIN_ID_ARRAY = [
  ETH_CHAIN_ID,
  POLYGON_CHAIN_ID,
  OPTIMISM_CHAIN_ID,
  ARBITRUM_CHAIN_ID,
  ZKSYNC_CHAIN_ID,
  BASE_CHAIN_ID,
]
