export const ETH_CHAIN_ID = 1
export const OPTIMISM_CHAIN_ID = 10
export const ARBITRUM_CHAIN_ID = 42161
export const BASE_CHAIN_ID = 8453
export const POLYGON_CHAIN_ID = 137
export const AURORA_CHAIN_ID = 1313161554
export const BSC_CHAIN_ID = 56
export const FANTOM_CHAIN_ID = 250
export const AVALANCHE_CHAIN_ID = 43114
export const MOONRIVER_CHAIN_ID = 1285
export const MOONBEAM_CHAIN_ID = 1284
export const METIS_CHAIN_ID = 1088
export const DFK_CHAIN_ID = 5395
export const CANTO_CHAIN_ID = 7700
export const CRONOS_CHAIN_ID = 25
export const DOGECHAIN_CHAIN_ID = 2000
export const KLAYTN_CHAIN_ID = 8217
export const BOBA_CHAIN_ID = 288

export const CHAIN_ID_ARRAY = [
  ETH_CHAIN_ID,
  POLYGON_CHAIN_ID,
  OPTIMISM_CHAIN_ID,
  ARBITRUM_CHAIN_ID,
  BASE_CHAIN_ID,
  BSC_CHAIN_ID,
  FANTOM_CHAIN_ID,
  AVALANCHE_CHAIN_ID,
  MOONBEAM_CHAIN_ID,
  MOONRIVER_CHAIN_ID,
  METIS_CHAIN_ID,
  DFK_CHAIN_ID,
  CANTO_CHAIN_ID,
  CRONOS_CHAIN_ID,
  DOGECHAIN_CHAIN_ID,
  KLAYTN_CHAIN_ID,
  BOBA_CHAIN_ID,
  AURORA_CHAIN_ID,
]
